### ISSUE TITLE
Prettifier config is sometimes ignored

### ISSUE THREAD

**Issue by erlichmen** [kevgo/prettifier#610]
I have a wired issue that Prettifier config is ignored (I have the config at the root in .prettierrc) and using the default config instead, It start happening for us today,
and it looks like the first commit of the PR ignores the config and when I pull, format locally, and push again it accept the config and doesn't try to format again.

**Comment by kevgo** [comment]
Sorry for the inconvenience. I was able to reproduce this and think I have fixed it. Can you please try again?

**Comment by erlichmen** [comment]
Look good to me

**Comment by kevgo** [comment]
Thanks for the detailed bug report @erlichmen, it helped fix this quickly!
