### ISSUE TITLE
Suggested improvements to the template that a user sees when they forget to format a file with Prettier

### ISSUE THREAD

**Issue by HonkingGoose** [kevgo/prettifier#620]
## Current bot message format:

```
Hey there! :wave: This repository uses the Prettier code style.

You forgot to format these files in your pull request:

   * docs/development/configuration.md
   * docs/development/local-development.md
   * docs/usage/docker.md

The [Prettier installation guide](https://prettier.io/docs/en/install.html)
is a good place to get started with formatting your code properly. Thanks!!

:heart:

Your friendly [Prettifier](https://www.prettifier.io/) bot
```

## Suggested bot message format:

```markdown
Hey there! :wave: This repository uses the Prettier code style.

You forgot to format these files in your pull request:

   * docs/development/configuration.md
   * docs/development/local-development.md
   * docs/usage/docker.md

The [Prettier installation guide](https://prettier.io/docs/en/install.html) is a good place to get started with formatting your code properly.
Thanks!

:heart:

Your friendly [Prettifier](https://www.prettifier.io/) bot.
```

## Suggested changes:

- Use one `!` instead of `!!`
- Put `is a good place to get started with formatting your code properly` together with the previous line.
- End last sentence with a `.`

## To reproduce:

See https://github.com/renovatebot/renovate/pull/7625#issuecomment-720120309

**Comment by kevgo** [comment]
Hi @HonkingGoose, thanks for the great suggestion, I like it! If you feel like it, feel free to submit a pull request that changes the [welcome message template](https://github.com/kevgo/prettifier/blob/master/bot/src/config/default-welcome.md.mustache) directly. Otherwise, I'm happy to change it myself tomorrow.

**Comment by HonkingGoose** [comment]
Incoming PR. :smile:
