### ISSUE TITLE
Feature: provide config for setting the commit message

### ISSUE THREAD

**Issue by wagerfield** [kevgo/prettifier#88]
For repos using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), it would be great if there was a way of specify the commit message eg. `chore: format {commitSha}` where `{commitSha}` is a template token that gets swapped out for [what you have here](https://github.com/kevgo/prettifier/blob/master/bot/src/index.ts#L111).

Thanks in advance :)

**Comment by kevgo** [comment]
Great idea! I'll add it to the backlog!

**Comment by kevgo** [comment]
@wagerfield I just implemented this. You are now able to add `commitMessage: "chore: format {{commitSha}}"` to your `.github/prettifier.yml` file. See https://kevgo.github.io/prettifier/docs/configuration for an example.

**Comment by wagerfield** [comment]
You sir are a legend. Thank you!
